name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
        
  trigger-cypress-tests:
    runs-on: ubuntu-22.04
    needs: [eslint, cypress-tests-desktop, cypress-tests-tablet]
    steps:
      - name: Trigger Cypress Tests in Another Repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/HectorOliveiraQA/Automacao-Afinando-main/dispatches \
            -d '{"event_type":"run-tests","client_payload":{"unit":false,"integration":true}}'
