name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint

  # cypress-tests-desktop:
  #   needs: eslint
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install modules
  #       run: npm install
  #     - name: Run end-to-end tests on desktop viewport 🧪
  #       uses: cypress-io/github-action@v5
  #       env:
  #         CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
  #         CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
  #         CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
  #         CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #       with:
  #         command: npm run test:cloud

  # # cypress-tests-tablet:
  # #   needs: eslint
  # #   runs-on: ubuntu-22.04
  # #   steps:
  # #     - uses: actions/checkout@v3
  # #     - name: Install modules
  # #       run: npm install
  # #     - name: Run end-to-end tests on tablet viewport 🧪
  # #       uses: cypress-io/github-action@v5
  # #       env:
  # #         CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
  # #         CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
  # #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  # #       with:
  # #         command: npm run test:tablet:cloud

  trigger-cypress-tests:
    runs-on: ubuntu-22.04
    needs: [eslint, cypress-tests-desktop, cypress-tests-tablet]
    steps:
      - name: Trigger Cypress Tests in Another Repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/HectorOliveiraQA/Automacao-Afinando-main/dispatches \
            -d '{"event_type":"run-tests","client_payload":{"unit":false,"integration":true}}'
